"""
Change history id to string.

Revision ID: 79f00a9f2409
Revises: adb5618bd4ee
Create Date: 2025-11-12 11:52:55.958100

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "79f00a9f2409"
down_revision: str | Sequence[str] | None = "adb5618bd4ee"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Change history_id from INTEGER to VARCHAR if needed
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_schema = 'public' AND table_name = 'citations' 
                  AND column_name = 'history_id'
                  AND data_type = 'integer'
            ) THEN
                ALTER TABLE citations ALTER COLUMN history_id TYPE VARCHAR USING history_id::text;
            END IF;
        END$$;
        """,
    )
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_schema = 'public' AND table_name = 'set_ingested_history' 
                  AND column_name = 'history_id'
                  AND data_type = 'integer'
            ) THEN
                ALTER TABLE set_ingested_history ALTER COLUMN history_id TYPE VARCHAR USING history_id::text;
            END IF;
        END$$;
        """,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "set_ingested_history",
        "history_id",
        existing_type=sa.String(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "citations",
        "history_id",
        existing_type=sa.String(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
