"""
Remove history table.

Revision ID: adb5618bd4ee
Revises: 843f6d216d10
Create Date: 2025-11-12 11:27:04.098561

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "adb5618bd4ee"
down_revision: str | Sequence[str] | None = "843f6d216d10"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Drop foreign key constraints if they exist
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM pg_constraint
                WHERE conrelid = 'citations'::regclass
                  AND conname = 'fk_citations_history'
            ) THEN
                ALTER TABLE citations DROP CONSTRAINT fk_citations_history;
            END IF;
        END$$;
        """,
    )
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM pg_constraint
                WHERE conrelid = 'set_ingested_history'::regclass
                  AND conname = 'set_ingested_history_history_id_fkey'
            ) THEN
                ALTER TABLE set_ingested_history DROP CONSTRAINT set_ingested_history_history_id_fkey;
            END IF;
        END$$;
        """,
    )
    # Drop history table if it exists
    op.execute("DROP TABLE IF EXISTS history CASCADE")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "history",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("content", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("history_pkey")),
    )
    op.create_foreign_key(
        op.f("set_ingested_history_history_id_fkey"),
        "set_ingested_history",
        "history",
        ["history_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_citations_history"),
        "citations",
        "history",
        ["history_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
